-- ============================================================================
-- Product Service - MySQL Seed Data
-- 10 categories + 100 products
--
--   USE product_service_db;
--   SOURCE /path/to/data.sql;
-- ============================================================================

USE product_service_db;

-- Clean slate (safe to re-run)
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE products;
TRUNCATE TABLE category;
SET FOREIGN_KEY_CHECKS = 1;

-- ----- Categories -----
INSERT INTO category (category_id, category_name, created_by, updated_by) VALUES (1, 'Electronics', 'SYSTEM', 'SYSTEM');
INSERT INTO category (category_id, category_name, created_by, updated_by) VALUES (2, 'Books', 'SYSTEM', 'SYSTEM');
INSERT INTO category (category_id, category_name, created_by, updated_by) VALUES (3, 'Clothing', 'SYSTEM', 'SYSTEM');
INSERT INTO category (category_id, category_name, created_by, updated_by) VALUES (4, 'Home & Kitchen', 'SYSTEM', 'SYSTEM');
INSERT INTO category (category_id, category_name, created_by, updated_by) VALUES (5, 'Sports & Outdoors', 'SYSTEM', 'SYSTEM');
INSERT INTO category (category_id, category_name, created_by, updated_by) VALUES (6, 'Toys & Games', 'SYSTEM', 'SYSTEM');
INSERT INTO category (category_id, category_name, created_by, updated_by) VALUES (7, 'Beauty & Personal Care', 'SYSTEM', 'SYSTEM');
INSERT INTO category (category_id, category_name, created_by, updated_by) VALUES (8, 'Grocery', 'SYSTEM', 'SYSTEM');
INSERT INTO category (category_id, category_name, created_by, updated_by) VALUES (9, 'Footwear', 'SYSTEM', 'SYSTEM');
INSERT INTO category (category_id, category_name, created_by, updated_by) VALUES (10, 'Furniture', 'SYSTEM', 'SYSTEM');

-- ----- Products -----
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (1, 'Apple iPhone 15 Pro 256GB', 'Flagship smartphone with A17 Pro chip', 129999.00, 337, 1, 'https://cdn.example.com/products/1.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (2, 'Samsung Galaxy S24 Ultra', 'Premium Android with S-Pen', 124999.00, 67, 1, 'https://cdn.example.com/products/2.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (3, 'Sony WH-1000XM5 Headphones', 'Industry-leading noise cancellation', 29990.00, 22, 1, 'https://cdn.example.com/products/3.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (4, 'Apple MacBook Air M3', '13-inch laptop with M3 chip', 114900.00, 389, 1, 'https://cdn.example.com/products/4.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (5, 'Dell XPS 13 Plus', 'Premium ultrabook with OLED display', 145000.00, 150, 1, 'https://cdn.example.com/products/5.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (6, 'iPad Air 11-inch M2', 'Tablet with M2 chip', 59900.00, 135, 1, 'https://cdn.example.com/products/6.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (7, 'Bose QuietComfort Ultra Earbuds', 'Premium wireless earbuds', 26900.00, 124, 1, 'https://cdn.example.com/products/7.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (8, 'LG 55-inch OLED C3 TV', '4K OLED smart TV', 159990.00, 81, 1, 'https://cdn.example.com/products/8.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (9, 'Canon EOS R6 Mark II', 'Full-frame mirrorless camera', 219990.00, 387, 1, 'https://cdn.example.com/products/9.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (10, 'Anker Soundcore Liberty 4', 'Hi-Res certified earbuds', 7999.00, 62, 1, 'https://cdn.example.com/products/10.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (11, 'Atomic Habits by James Clear', 'Bestselling habit formation guide', 499.00, 356, 2, 'https://cdn.example.com/products/11.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (12, 'The Psychology of Money', 'Timeless lessons on wealth and happiness', 399.00, 389, 2, 'https://cdn.example.com/products/12.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (13, 'Clean Code by Robert Martin', 'Handbook of agile software craftsmanship', 899.00, 466, 2, 'https://cdn.example.com/products/13.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (14, 'Designing Data-Intensive Apps', 'Big ideas behind reliable systems', 1199.00, 289, 2, 'https://cdn.example.com/products/14.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (15, 'Sapiens by Yuval Noah Harari', 'A brief history of humankind', 599.00, 54, 2, 'https://cdn.example.com/products/15.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (16, 'The Pragmatic Programmer', 'Your journey to mastery', 999.00, 312, 2, 'https://cdn.example.com/products/16.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (17, 'Deep Work by Cal Newport', 'Rules for focused success', 499.00, 226, 2, 'https://cdn.example.com/products/17.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (18, 'Thinking Fast and Slow', 'Daniel Kahneman classic', 549.00, 26, 2, 'https://cdn.example.com/products/18.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (19, 'Effective Java 3rd Edition', 'Best practices for the Java platform', 1399.00, 25, 2, 'https://cdn.example.com/products/19.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (20, 'Domain-Driven Design', 'Tackling complexity in the heart of software', 1599.00, 57, 2, 'https://cdn.example.com/products/20.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (21, 'Levi''s 511 Slim Fit Jeans', 'Classic slim-fit denim', 2999.00, 121, 3, 'https://cdn.example.com/products/21.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (22, 'Nike Dri-FIT T-Shirt', 'Moisture-wicking training tee', 1295.00, 129, 3, 'https://cdn.example.com/products/22.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (23, 'Allen Solly Formal Shirt', 'Cotton full-sleeve formal shirt', 1799.00, 268, 3, 'https://cdn.example.com/products/23.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (24, 'H&M Hooded Sweatshirt', 'Cotton-blend pullover hoodie', 1499.00, 318, 3, 'https://cdn.example.com/products/24.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (25, 'Zara Slim-Fit Blazer', 'Smart-casual single breasted blazer', 5990.00, 23, 3, 'https://cdn.example.com/products/25.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (26, 'Tommy Hilfiger Polo', 'Classic-fit pique polo', 2499.00, 297, 3, 'https://cdn.example.com/products/26.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (27, 'Wrangler Skinny Jeans', 'Mid-rise skinny denim', 2199.00, 111, 3, 'https://cdn.example.com/products/27.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (28, 'Puma Track Pants', 'Athletic-fit jogger pants', 1799.00, 376, 3, 'https://cdn.example.com/products/28.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (29, 'Peter England Chinos', 'Tailored cotton chinos', 2399.00, 342, 3, 'https://cdn.example.com/products/29.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (30, 'UCB Crew-Neck Sweater', 'Wool-blend pullover', 2799.00, 369, 3, 'https://cdn.example.com/products/30.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (31, 'Prestige 3-Burner Gas Stove', 'Stainless steel gas hob', 4999.00, 289, 4, 'https://cdn.example.com/products/31.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (32, 'Philips Air Fryer HD9252', 'Rapid Air technology fryer', 9999.00, 224, 4, 'https://cdn.example.com/products/32.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (33, 'Bosch 7kg Front Load Washer', 'Energy-efficient washing machine', 38999.00, 122, 4, 'https://cdn.example.com/products/33.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (34, 'Milton Thermosteel Flask 1L', '24-hr hot/cold flask', 999.00, 239, 4, 'https://cdn.example.com/products/34.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (35, 'Pigeon Favourite Pressure Cooker 5L', 'Aluminium induction-base cooker', 1499.00, 311, 4, 'https://cdn.example.com/products/35.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (36, 'Cello Plastic Storage Containers Set', 'Set of 10 airtight containers', 799.00, 152, 4, 'https://cdn.example.com/products/36.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (37, 'Hawkins Contura Nonstick Tawa', '27cm nonstick flat pan', 999.00, 424, 4, 'https://cdn.example.com/products/37.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (38, 'LG 260L Double Door Fridge', 'Smart Inverter Compressor', 28990.00, 455, 4, 'https://cdn.example.com/products/38.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (39, 'Bajaj Mixer Grinder 750W', '3-jar mixer grinder', 3499.00, 13, 4, 'https://cdn.example.com/products/39.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (40, 'Borosil Glass Mixing Bowl Set', 'Set of 3 microwave-safe bowls', 899.00, 398, 4, 'https://cdn.example.com/products/40.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (41, 'Wilson Tennis Racquet Pro Staff', 'Tournament-grade racquet', 14999.00, 422, 5, 'https://cdn.example.com/products/41.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (42, 'SG Cricket Bat English Willow', 'Senior-size short-handle bat', 7999.00, 91, 5, 'https://cdn.example.com/products/42.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (43, 'Nivia Football Storm Size 5', 'Hand-stitched rubber football', 599.00, 367, 5, 'https://cdn.example.com/products/43.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (44, 'Cosco Yoga Mat 6mm', 'Anti-skid TPE yoga mat', 899.00, 226, 5, 'https://cdn.example.com/products/44.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (45, 'Decathlon Backpack 30L', 'Hiking and trekking backpack', 1999.00, 184, 5, 'https://cdn.example.com/products/45.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (46, 'Bike Helmet ISI-Marked', 'Ventilated cycling helmet', 1299.00, 152, 5, 'https://cdn.example.com/products/46.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (47, 'Boldfit Dumbbell Set 10kg', 'Pair of vinyl-coated dumbbells', 1499.00, 89, 5, 'https://cdn.example.com/products/47.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (48, 'Yonex Badminton Racket', 'Lightweight aluminium frame', 2299.00, 120, 5, 'https://cdn.example.com/products/48.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (49, 'Stanley Insulated Bottle 750ml', 'Vacuum-insulated stainless flask', 2299.00, 500, 5, 'https://cdn.example.com/products/49.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (50, 'Adidas Football Boots', 'Firm-ground studded boots', 4999.00, 400, 5, 'https://cdn.example.com/products/50.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (51, 'LEGO Classic Creative Bricks', '484 piece building set', 3499.00, 182, 6, 'https://cdn.example.com/products/51.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (52, 'Rubik''s Cube 3x3 Speed Cube', 'Smooth-turning speed cube', 599.00, 62, 6, 'https://cdn.example.com/products/52.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (53, 'Hot Wheels 20-Car Gift Pack', 'Die-cast vehicles collection', 1999.00, 57, 6, 'https://cdn.example.com/products/53.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (54, 'Funskool Monopoly Board Game', 'Classic family board game', 999.00, 204, 6, 'https://cdn.example.com/products/54.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (55, 'Barbie Dreamhouse', '3-storey dollhouse playset', 14999.00, 59, 6, 'https://cdn.example.com/products/55.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (56, 'Nerf Elite Disruptor Blaster', '6-dart blaster', 1799.00, 193, 6, 'https://cdn.example.com/products/56.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (57, 'Catan Board Game', 'Strategy resource-trading game', 2499.00, 443, 6, 'https://cdn.example.com/products/57.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (58, 'Play-Doh 10-Pack Modeling Compound', 'Non-toxic modeling clay', 499.00, 186, 6, 'https://cdn.example.com/products/58.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (59, 'Uno Card Game', 'Classic family card game', 199.00, 319, 6, 'https://cdn.example.com/products/59.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (60, 'Remote Control Drone with Camera', 'HD-camera quadcopter drone', 4999.00, 145, 6, 'https://cdn.example.com/products/60.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (61, 'Dove Beauty Bar 4-pack', 'Moisturizing bath soap', 199.00, 423, 7, 'https://cdn.example.com/products/61.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (62, 'Loreal Paris Total Repair Shampoo', 'Damage-repair shampoo 650ml', 599.00, 32, 7, 'https://cdn.example.com/products/62.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (63, 'Maybelline Fit Me Foundation', 'Matte and poreless foundation', 499.00, 383, 7, 'https://cdn.example.com/products/63.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (64, 'Nivea Body Lotion 400ml', 'Nourishing body lotion', 349.00, 245, 7, 'https://cdn.example.com/products/64.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (65, 'Gillette Mach3 Razor', '3-blade manual razor', 299.00, 284, 7, 'https://cdn.example.com/products/65.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (66, 'Forest Essentials Face Wash', 'Ayurvedic gentle cleanser', 1095.00, 73, 7, 'https://cdn.example.com/products/66.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (67, 'Mamaearth Vitamin C Serum', 'Brightening face serum', 599.00, 482, 7, 'https://cdn.example.com/products/67.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (68, 'Philips Norelco Beard Trimmer', 'Cordless USB-charging trimmer', 2999.00, 203, 7, 'https://cdn.example.com/products/68.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (69, 'Cetaphil Moisturizing Cream 250g', 'Dermatologist-recommended cream', 799.00, 50, 7, 'https://cdn.example.com/products/69.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (70, 'Pond''s Talcum Powder 400g', 'Refreshing fragrance talc', 199.00, 292, 7, 'https://cdn.example.com/products/70.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (71, 'Tata Salt 1kg', 'Iodized vacuum-evaporated salt', 28.00, 160, 8, 'https://cdn.example.com/products/71.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (72, 'Aashirvaad Atta 5kg', '100% whole wheat flour', 280.00, 434, 8, 'https://cdn.example.com/products/72.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (73, 'Fortune Sunlite Refined Sunflower Oil 1L', 'Refined cooking oil', 165.00, 331, 8, 'https://cdn.example.com/products/73.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (74, 'Maggi 2-Minute Noodles Pack of 12', 'Masala instant noodles', 168.00, 326, 8, 'https://cdn.example.com/products/74.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (75, 'Nescafe Classic Coffee 200g', 'Pure instant coffee', 590.00, 463, 8, 'https://cdn.example.com/products/75.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (76, 'Amul Pure Ghee 1L Tin', 'Cow-milk pure ghee', 600.00, 451, 8, 'https://cdn.example.com/products/76.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (77, 'Tata Tea Premium 1kg', 'Strong dust black tea', 535.00, 195, 8, 'https://cdn.example.com/products/77.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (78, 'Surf Excel Matic Liquid Detergent 2L', 'Front-load matic detergent', 460.00, 305, 8, 'https://cdn.example.com/products/78.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (79, 'MDH Garam Masala 100g', 'Authentic Indian spice blend', 99.00, 108, 8, 'https://cdn.example.com/products/79.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (80, 'Britannia Marie Gold Biscuits Pack of 12', 'Classic tea biscuits', 240.00, 370, 8, 'https://cdn.example.com/products/80.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (81, 'Nike Revolution 6 Running Shoes', 'Lightweight road-running shoes', 3495.00, 45, 9, 'https://cdn.example.com/products/81.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (82, 'Adidas Ultraboost 22', 'Premium running sneakers', 17999.00, 33, 9, 'https://cdn.example.com/products/82.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (83, 'Puma Smash V2 Sneakers', 'Casual leather sneakers', 2999.00, 348, 9, 'https://cdn.example.com/products/83.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (84, 'Bata Formal Oxford Shoes', 'Genuine leather lace-ups', 2499.00, 126, 9, 'https://cdn.example.com/products/84.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (85, 'Crocs Classic Clogs', 'Iconic comfort clogs', 2995.00, 405, 9, 'https://cdn.example.com/products/85.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (86, 'Woodland Leather Boots', 'Outdoor genuine leather boots', 4999.00, 158, 9, 'https://cdn.example.com/products/86.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (87, 'Sparx Casual Slip-Ons', 'Everyday casual shoes', 999.00, 50, 9, 'https://cdn.example.com/products/87.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (88, 'Liberty Formal Shoes', 'Synthetic leather slip-ons', 1799.00, 447, 9, 'https://cdn.example.com/products/88.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (89, 'Skechers Go Walk 5', 'Air-cooled memory foam walkers', 4499.00, 129, 9, 'https://cdn.example.com/products/89.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (90, 'Reebok Floatride Run', 'High-cushion running shoes', 7499.00, 453, 9, 'https://cdn.example.com/products/90.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (91, 'Sleepwell Mattress Queen Size', 'Memory-foam orthopedic mattress', 24999.00, 61, 10, 'https://cdn.example.com/products/91.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (92, 'IKEA POÄNG Armchair', 'Bentwood-frame relaxing chair', 8999.00, 204, 10, 'https://cdn.example.com/products/92.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (93, 'Urban Ladder Dining Table 6-Seater', 'Sheesham-wood dining table', 32999.00, 152, 10, 'https://cdn.example.com/products/93.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (94, 'Godrej Storewell 3-Door Wardrobe', 'Steel 3-door wardrobe', 21999.00, 242, 10, 'https://cdn.example.com/products/94.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (95, 'Featherlite Office Chair', 'Ergonomic mesh-back chair', 8499.00, 335, 10, 'https://cdn.example.com/products/95.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (96, 'Pepperfry Sofa Cum Bed', 'Convertible 3-seater sofa bed', 18999.00, 437, 10, 'https://cdn.example.com/products/96.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (97, 'Nilkamal Plastic Chair', 'Sturdy moulded plastic chair', 999.00, 196, 10, 'https://cdn.example.com/products/97.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (98, 'HomeTown Bookshelf 5-Tier', 'Engineered wood bookshelf', 5499.00, 93, 10, 'https://cdn.example.com/products/98.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (99, 'Wakefit Bed King Size', 'Solid-wood platform bed', 19999.00, 199, 10, 'https://cdn.example.com/products/99.jpg', 'SYSTEM', 'SYSTEM');
INSERT INTO products (product_id, product_name, description, price, stock, category_id, image_url, created_by, updated_by) VALUES (100, 'Casa Copenhagen Bean Bag XXL', 'Filled XXXL bean bag with beans', 1499.00, 191, 10, 'https://cdn.example.com/products/100.jpg', 'SYSTEM', 'SYSTEM');

-- Verify counts
-- SELECT (SELECT COUNT(*) FROM category) AS categories,
--        (SELECT COUNT(*) FROM products) AS products;
