package com.cts.productservice.entity;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * JPA entity representing a product category persisted in the {@code category} table.
 * <p>
 * A category is a logical grouping that one or more {@link Product} records may
 * belong to. Auditing fields are populated automatically by Spring Data JPA through
 * the registered {@link AuditingEntityListener}. Lombok generates the constructors,
 * accessors, and builder for this class.
 *
 * @since 1.0
 */
@Entity
@Table(name = "category")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Category {

    /** Surrogate primary key, auto-generated by the database identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "category_id")
    private Long categoryId;

    /** Unique, human-readable category name (maximum 100 characters). */
    @Column(name = "category_name", nullable = false, unique = true, length = 100)
    private String categoryName;

    /* ------------ Auditing ------------ */

    /** Timestamp captured when the row was first persisted; never subsequently updated. */
    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp refreshed each time the row is modified. */
    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /** Identifier of the user who created the row, resolved from the configured auditor. */
    @CreatedBy
    @Column(name = "created_by", updatable = false, length = 50)
    private String createdBy;

    /** Identifier of the user who last modified the row, resolved from the configured auditor. */
    @LastModifiedBy
    @Column(name = "updated_by", length = 50)
    private String updatedBy;
}
