package com.cts.productservice.entity;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * JPA entity representing a sellable product persisted in the {@code products} table.
 * <p>
 * Every product belongs to exactly one {@link Category} and tracks its own price
 * and inventory level. Auditing fields are populated automatically by Spring Data
 * JPA through the registered {@link AuditingEntityListener}. Lombok generates the
 * constructors, accessors, and builder for this class.
 *
 * @since 1.0
 */
@Entity
@Table(name = "products")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Product {

    /** Surrogate primary key, auto-generated by the database identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "product_id")
    private Long productId;

    /** Display name of the product (maximum 255 characters); required. */
    @Column(name = "product_name", nullable = false, length = 255)
    private String productName;

    /** Optional free-text description of the product (maximum 500 characters). */
    @Column(length = 500)
    private String description;

    /** Unit price of the product; required and expected to be positive. */
    @Column(nullable = false)
    private Double price;

    /** Current inventory level; required and defaults to {@code 0} for newly built products. */
    @Column(nullable = false)
    @Builder.Default
    private Integer stock = 0;

    /** Owning {@link Category}; mandatory and loaded lazily to avoid unnecessary joins. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    /** Optional URL pointing to the product image (maximum 500 characters). */
    @Column(name = "image_url", length = 500)
    private String imageUrl;

    /* ------------ Auditing ------------ */

    /** Timestamp captured when the row was first persisted; never subsequently updated. */
    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp refreshed each time the row is modified. */
    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /** Identifier of the user who created the row, resolved from the configured auditor. */
    @CreatedBy
    @Column(name = "created_by", updatable = false, length = 50)
    private String createdBy;

    /** Identifier of the user who last modified the row, resolved from the configured auditor. */
    @LastModifiedBy
    @Column(name = "updated_by", length = 50)
    private String updatedBy;
}
